### ISSUE TITLE
ethernet not working on mcvevk

### ISSUE THREAD

**Issue by flofeurstein** [ARIES-Embedded/meta-aries#1]
## Description

* Environment: defaults on `kirkstone` branch. 
* MCV: MCV-X2DB V3.4
* Eval board: MCVEVP Version 2.0

Ethernet does not work on the `mcvevk` when using the `kirkstone` branch. It worked perfectly on `dunfell`.

Connecting/unconnecting the ethernet cable shows the following entries in the syslog:

![image](https://user-images.githubusercontent.com/1737745/185029165-7d1e195e-d6dc-4ea2-88a5-bb39089441d2.png)

### Problem

* cannot get IP address when `dhcp` mode is set in `/etc/network/interfaces`
![image](https://user-images.githubusercontent.com/1737745/185024029-3036c086-68c5-4c59-a7c7-725cb4dfe65a.png)
  * according to logs `udhcpc` broadcasts discover but never gets an IP
![image](https://user-images.githubusercontent.com/1737745/185027277-089f80eb-71d7-4acb-ae2f-845ef4fa3f56.png)

* when setting a static ip in `/etc/network/interfaces`, `ifconfig` shows the correct static IP address, but pinging or connecting via ssh fails
![image](https://user-images.githubusercontent.com/1737745/185026604-13f82809-75c7-4cb9-ad5f-fb4ac6e229ba.png)

### Reproduce Error

* checkout and build `kirkstone` branch according to the `README.md`
* write the image to the `mcv`
* check ethernet connection on `mcvevk`.

## Logs

[logs.zip](https://github.com/ARIES-Embedded/meta-aries/files/9355966/logs.zip)

**Comment by grandwolf** [comment]
Thanks for your issue report, I have just pushed a fix for this issue restoring the "old" skew values for the KSZ9031 phy. As expected, the problem was caused by the "linux-socfpga" commit:

`commit bcf3440c6dd78bfe5836ec0990fe36d7b4bb7d20
Author: Oleksij Rempel <linux@rempel-privat.de>
Date:   Wed Apr 22 09:21:37 2020 +0200

    net: phy: micrel: add phy-mode support for the KSZ9031 PHY
    
    Add support for following phy-modes: rgmii, rgmii-id, rgmii-txid, rgmii-rxid.
    
    This PHY has an internal RX delay of 1.2ns and no delay for TX.
    
    The pad skew registers allow to set the total TX delay to max 1.38ns and
    the total RX delay to max of 2.58ns (configurable 1.38ns + build in
    1.2ns) and a minimal delay of 0ns.
    
    According to the RGMII v1.3 specification the delay provided by PCB traces
    should be between 1.5ns and 2.0ns. The RGMII v2.0 allows to provide this
    delay by MAC or PHY. So, we configure this PHY to the best values we can
    get by this HW: TX delay to 1.38ns (max supported value) and RX delay to
    1.80ns (best calculated delay)
    
    The phy-modes can still be fine tuned/overwritten by *-skew-ps
    device tree properties described in:
    Documentation/devicetree/bindings/net/micrel-ksz90x1.txt
    
    Signed-off-by: Oleksij Rempel <o.rempel@pengutronix.de>
    Reviewed-by: Philippe Schenker <philippe.schenker@toradex.com>
    Reviewed-by: Andrew Lunn <andrew@lunn.ch>
    Signed-off-by: David S. Miller <davem@davemloft.net>`

which changed the skew values.

**Comment by flofeurstein** [comment]
Fixed with https://github.com/ARIES-Embedded/meta-aries/commit/ff68f7b9ecc29e7bb24181aeee00cc714f0fad16
